이메일 인증
boardStudy/BoardStudy pull request #103
Opened 2022-05-13 19:19 UTC by dahoon1006

# 해결하려는 문제가 무엇인가요?
1. 이메일 인증번호로 인증하기
2. 이메일 인증링크 클릭 시 인증하기

이번 프로젝트에서는 후자를 선택했습니다.

# 어떻게 해결했나요?
1. 회원가입 시에 입력한 이메일로 인증링크 발송.
: emailProperties > 인증 링크 안에 userId + key를 넣어 고유값 생성 후 전송. 
2. 회원가입 시 TBL_USER 테이블 컬럼 USER_AUTH(DEFAULT 0)로 가입됨.
3. 전송 받은 인증 링크 클릭 시 alert창 출력 및 로그인 페이지를 표시하기 위해 resisterEmail.html으로 이동.
: 인증 링크 클릭과 함께 USER_AUTH 0 > 1 업데이트.
: 기존 로그인 로직에서 user.getUserAuth()을 추가해 인증 여부 확인. 
4. 이메일 미인증 회원이 로그인 시도 시
: 메일 미인증 상태를 표시하기 위해 resisterNotCertified.html으로 이동.

2022-05-14 02:28 UTC, DaeAkin requested changes
db 비밀번호 다 노출 되었네요.

2022-05-14 14:24 UTC, lovi0714 commented
이미 유출된 비밀번호여서 설정은 원래대로 환경 변수로 처리하고 DB 비밀번호 바꾸는 게 어떠신가여?

2022-05-14 15:34 UTC, DaeAkin commented on src/main/java/com/hoin/boardStudy/user/dto/EmailProperties.java
> +            "<br/><a href='http://localhost:8080/user/registerEmail?email=%s&key=%s'>이메일 인증하기</a>" +
환경에 따른 도메인 선택 으로 변경해주세요.

2022-05-15 14:14 UTC, DaeAkin approved these changes

2022-05-15 14:19 UTC, merged