읽은 글 처리하기
boardStudy/BoardStudy pull request #126
Opened 2022-09-23 23:59 UTC by lovi0714

# 해결하려는 문제가 무엇인가요?
* new 글 기준인 2일이 지나지 않았더라도 읽은 글은 new 표시를 없애는 기능 구현

# 어떻게 해결했나요?
* ``TBL_READ`` 라는 테이블을 생성하고 ``board_id``,``user_id``라는 컬럼을 생성했습니다.
* 읽지 않은 글이라면 상세보기로 글을 읽게 될 때, 로그인 중인 아이디 (user_id)와 해당 글(board_id)가 저장될 수 있도록 했습니다.
* count 함수 밖에 알지 못했었는데 DBMS 특성 상 데이터가 많아질수록 성능이 떨어진다는 사실을 발견했습니다. 그래서 이번엔 exists 연산자를 사용하여 원하는 데이터가 있는지 없는지 boolean 타입을 리턴 받을 수 있도록 구현했습니다.
* 저번에 ``DateChecker``로 이름을 변경했던 클래스는 다시 ``NewArticleChecker``라는 이름으로 변경하고, private으로 날짜 확인, 읽은 글 확인하는 메서드를 작성하여 public ``checkNewArticle()`` 이라는 메서드로 검사할 수 있도록 작성했습니다.
* ``Board``에 있던 ``expirationOrNot`` 은 ``newOrNot``으로 변경했습니다.

로그인 한 유저의 userId 처리 때문에 고민을 많이 했는데 결국 session 처리는 컨트롤러 단에서 밖에 할 수 없고 (service 단으로 넘어가게 되면 의존성이 커짐) 코드가 너무 지저분하다고 느꼈습니다. 비로그인 시 매개변수로 받는 userId 때문에 필요없는 null 값이 넘어가는 상황..

로그인과 비로그인 두 가지 경우의 수가 있기 때문에 
차라리 오버로딩을 통해 로그인, 비로그인 시 나눠서 필요한 기능만 동작하게끔 하자 라는 결론을 내렸습니다. 이게 맞는지는 잘..

* getDetail() 메서드에 붙어있던 readOnly는 처음 읽는 글일 때 아이디와 글 번호를 insert하는 동작이 추가 되었으므로 제거했습니다.
* ``TBL_READ``에 저장되어있는 정보의 처리는 아직 건드리지 않았습니다. (일정 시간 후 삭제한다던가) 
* 다음에 본인이 읽은 글 목록을 볼 수 있는 기능을 구현하면서 처리해보겠습니다.

아 추가로 mybatis 사용하면서 #이랑 $의 차이를 모르고 그냥 썼는데 이번에 차이점을 알게 됐습니다. # $ 차이점 정리하면서 sql injection까지 정리해보겠습니다.

## Attachment
* https://kkh0977.tistory.com/1141

2022-09-26 15:18 UTC, DaeAkin requested changes

2022-09-26 15:18 UTC, DaeAkin commented on src/main/java/com/hoin/boardStudy/board/controller/BoardController.java
> +        }
이 로직이 있어서 한눈에 보기 힘든 단점이 있는거 같네요

이 부분만 private 메서드로 분리해서 가독성을 높이는건 어떨까요

2022-09-26 15:18 UTC, DaeAkin commented on src/main/java/com/hoin/boardStudy/board/controller/BoardController.java
> +        }
getDetailPage() 내부에 있는 애들하고도 중복이긴하네요

2022-09-26 15:18 UTC, DaeAkin commented on src/main/java/com/hoin/boardStudy/board/service/BoardService.java
> +    }
위 아래랑 로직이 대부분 같은데, 같이 쓰면 좋을듯

user가 없으면 userId에 null을 넘겨줘서 널에 따라서 분기하는방법으로

2022-09-26 15:18 UTC, DaeAkin commented on src/main/java/com/hoin/boardStudy/board/service/BoardService.java
> +        if(!boardMapper.isItRead(boardId, userId)) boardMapper.checkReadArticle(boardId, userId);
isItRead보단 isRead가 어울리지 않을까싶음

2022-09-26 15:18 UTC, DaeAkin commented on src/main/java/com/hoin/boardStudy/board/service/BoardService.java
> +            if(newArticleChecker.checkNewArticle(boardId, EXPIRY_PERIOD)) board.setNewOrNot(true);
새글을 확인하기 위해 쿼리가 몇번 나가게 되는지 한번 생각해볼 필요가 있을듯

쿼리를 최대한 줄이는 방법은 뭐가 있을지 고민해봐야할듯

2022-09-30 01:36 UTC, lovi0714 commented
[154e15b](https://github.com/boardStudy/BoardStudy/pull/126/commits/154e15b716f9964025183473289638f62751f4ae) 커밋내용

1. 요청받은 페이지 정보(page, pageSize)를 가공하는 과정을 단계별로 메서드 처리하여 가독성을 높이려 했습니다.
2. isItRead -> isRead로 변경했습니다.
3. null 처리 방식(로그인, 비로그인)에 대해서는 이번 커밋 이후 다시 논의 후 처리해보겠습니다.
4. 마지막 리뷰는 아직 고민 중..

2022-10-03 04:54 UTC, lovi0714 commented
[470ae18](https://github.com/boardStudy/BoardStudy/pull/126/commits/470ae189f526fbdf5bfef868c9a3321b687c97ff) 커밋내용

기존에 새 글을 확인하기 위해 ``boardId``만 매개변수로 넘기던 것을 ``Board``를 넘겨주어 등록일을 따로 불러올 필요 없도록 변경했습니다.

2022-10-03 06:58 UTC, lovi0714 commented
[66356b3](https://github.com/boardStudy/BoardStudy/pull/126/commits/66356b31b09b4f0bb4283a99f6b5a5c489e50a29) 커밋내용

1.
기존 새글인지 아닌지 판별하기 위해 등록일을 가져올 때, 게시글마다 boardMapper.detail(boardId).getRegDate 이런 식으로 게시물마다 쿼리를 불러오는 문제점이 있었습니다.

그래서 매개 변수로 board를 넘겨주어 board에 있는 board.getRegdate를 활용해 쿼리를 쓰지 않고도 등록일을 구할 수 있게 개선했습니다.

2.
총 게시물 갯수를 2번 구해오는 문제점이 있어 값을 구해 변수로 선언해두고 재사용하여 두 번 구해오지 않도록 변경했습니다.

결과 : 이 두번의 과정을 통해 쿼리 9번 -> 3번으로 줄이는 결과를 얻을 수 있었고, 이는 게시물 1개당 쿼리 1번을 불러와야 했던 방식이었기 때문에 게시물이 많아지면 많아질수록 큰 차이가 났을 것입니다.

2022-10-03 13:15 UTC, DaeAkin approved these changes

2022-10-03 13:16 UTC, merged